spring:
  mvc:
    async:
      request-timeout: 300
    date-format: DD/MM/YY
    servlet:
      load-on-startup: -1
  social:
    auto-connection-views: false
  thymeleaf:
    cache: true
    check-template: true
    check-template-location: true
  webservices:
    path: /services

